name: Docker Image CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Log in to ghcr registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build CPU image
      run: docker build . --file cpu.Dockerfile --tag ghcr.io/kbegiedza/pytorch-jupyter:1.10-cpu

    - name: Build CUDA image
      run: docker build . --file cuda.Dockerfile --tag ghcr.io/kbegiedza/pytorch-jupyter:1.10-cuda
    
    - name: Publish CPU image
      run: docker push ghcr.io/kbegiedza/pytorch-jupyter:1.10-cpu
    
    - name: Publish CUDA image
      run: docker push ghcr.io/kbegiedza/pytorch-jupyter:1.10-cuda
